### ISSUE TITLE
local monkey patching

### ISSUE THREAD

**Issue by francescoagati** [back2dos/no-spoon#2]
this library can be use for a local monkey patching? for example change code only inside namespaces?
imagine for example the refinements in ruby with a local monkey patching

**Comment by back2dos** [comment]
Hmm, I'm not sure what you mean by that. Perhaps you could give me an example?

**Comment by francescoagati** [comment]
apply some transformations but only in some local namespaces but not global.

2018-04-17 14:44 GMT+02:00 Juraj Kirchheim <notifications@github.com>:

**Comment by back2dos** [comment]
That's not an example ;)

**Comment by francescoagati** [comment]
imagine this pseudo code

no.Spoon.replace('Math', macro : FastMath,
{only_in_namespaces:['lib.a.*','lib.b.*']} );



2018-04-17 15:27 GMT+02:00 Juraj Kirchheim <notifications@github.com>:

**Comment by back2dos** [comment]
Ok, and in that case any mention of `Math` in `lib.a.*` should refer to `FastMath`? In that case, it's not possible in general. The case of `Math` is a bit particular, because it's a top level class (more precisely, it's in a parent package of `lib.a`) so if you `no.Spoon.replace('lib.a.Math', macro : FastMath)` then incidentally haxe will resolve `Math` to `FastMath` within `lib.a`. That said, `import Math.*;` will still pull in the toplevel `Math`.
